### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by kam193** [jorenham/optype#210]
There is definitely a missing reference documentation for `optype.rick`.

**Comment by jorenham** [comment]
> "stop digging for hidden layers and just be impressed"

**Comment by jorenham** [comment]
but feel free to open a PR

**Comment by kam193** [comment]
As soon as I finish digging for hidden layers :saluting_face:

**Comment by jorenham** [comment]
> As soon as I finish digging for hidden layers 🫡

🤭
